# This will load the arrf file and converts it into pandas dataframe so that you can perform pandas operations.

### Importing Relevant Libraries

In [1]:
from scipy.io.arff import loadarff
import numpy as np
import pandas as pd
print('relevant libraries uploaded')

relevant libraries uploaded


### Loading arff File

In [2]:
filepath = '../CICDataSet-TOR/CSV/Scenario-A/TimeBasedFeatures-15s-TOR-NonTOR.arff'
raw_data = loadarff(filepath)

In [46]:
raw_data

(array([( 9368711., 1.6000000e+01, 4.0000000e+00, 1.564818e+06, 1.549373e+06,  190205.28571429,  203290.45652174,  389822.39191658,  370323.71975366, 10.35361215,  4802.68843814,  4., 1523088.,  97590.73958333,  267600.19844335,  1.871488e+06, 1983656.33333333,  2.195089e+06,  183219.69791437,  1.234883e+06, 1420565.,  1.523088e+06,  161096.53927537, b'NONTOR'),
        ( 7340238., 1.8000000e+01, 4.0000000e+00, 1.567554e+06, 1.527893e+06,  165686.97727273,  186914.84615385,  317267.5487422 ,  304370.65130139, 11.58000599,  4340.18624464,  4., 1517774.,  87383.78571429,  221462.86202794,  1.491627e+06, 3572433.        ,  5.653239e+06, 2942704.06586714,  1.131498e+06, 1324636.,  1.517774e+06,  273138.37900778, b'NONTOR'),
        ( 4644225., 2.9000000e+01, 1.5000000e+01, 1.270547e+06, 1.079974e+06,  165865.17857143,  195302.13043478,  329473.12626076,  300492.58822667, 11.41202246,  4161.51241596, 15., 1079974.,  89312.01923077,  217475.42524643,  1.758922e+06, 1758922.        ,  1.75892

### Converting into pandas dataframe

In [4]:
df_data = pd.DataFrame(raw_data[0])

For some reason, when I convert into pandas dataframe, in the column name class1, each row has a character 'b' infront of the traffic name. I have fixed it in line 57 below.

In [5]:
df_data

duration  total_fiat  total_biat   min_fiat   min_biat      max_fiat  \
0       9368711.0        16.0         4.0  1564818.0  1549373.0  1.902053e+05   
1       7340238.0        18.0         4.0  1567554.0  1527893.0  1.656870e+05   
2       4644225.0        29.0        15.0  1270547.0  1079974.0  1.658652e+05   
3       4978735.0        19.0         8.0  2492050.0  2457286.0  2.395432e+05   
4      11838189.0        19.0        10.0  3094089.0  3093543.0  2.437665e+05   
...           ...         ...         ...        ...        ...           ...   
22067  13932812.0  13932390.0  13932812.0       93.0      244.0  8.119562e+06   
22068  14999975.0  14999975.0  14961989.0        0.0        7.0  1.624147e+06   
22069  14660517.0  14660517.0  14618019.0      333.0      613.0  7.663754e+06   
22070  14832948.0  14832905.0  14792242.0        7.0       12.0  7.884760e+05   
22071  14633355.0  14633355.0  14632000.0        6.0       34.0  1.707112e+06   

           max_biat     mean_fiat     mean_biat  flowPktsPerSecond  ...  \
0      2.032905e+05  3.898224e+05  3.703237e+05          10.353612  ...   
1      1.869148e+05  3.172675e+05  3.043707e+05          11.580006  ...   
2      1.953021e+05  3.294731e+05  3.004926e+05          11.412022  ...   
3      2.765964e+05  6.124353e+05  6.283396e+05           8.034169  ...   
4      2.959547e+05  5.997218e+05  6.256327e+05           7.602514  ...   
...             ...           ...           ...                ...  ...   
22067  8.081967e+06  3.240091e+05  2.843431e+05           6.746664  ...   
22068  1.624060e+06  2.103783e+04  2.939487e+04          81.600136  ...   
22069  7.663955e+06  1.628946e+06  1.827252e+06           1.295998  ...   
22070  8.250180e+05  4.324462e+04  4.350659e+04          46.180975  ...   
22071  1.707109e+06  4.180959e+04  4.766124e+04          45.034102  ...   

        std_flowiat  min_active   mean_active  max_active    std_active  \
0      2.676002e+05   1871488.0  1.983656e+06   2195089.0  1.832197e+05   
1      2.214629e+05   1491627.0  3.572433e+06   5653239.0  2.942704e+06   
2      2.174754e+05   1758922.0  1.758922e+06   1758922.0  0.000000e+00   
3      4.369597e+05   1710925.0  2.382905e+06   3054885.0  9.503232e+05   
4      4.361296e+05   1747431.0  2.400446e+06   3240696.0  6.232744e+05   
...             ...         ...           ...         ...           ...   
22067  8.490494e+05   1506874.0  6.966222e+06  12425570.0  7.720684e+06   
22068  7.020772e+04   3249302.0  3.525820e+06   3802338.0  3.910555e+05   
22069  2.116241e+06   6381394.0  7.023854e+06   7666315.0  9.085764e+05   
22070  6.915061e+04        -1.0  0.000000e+00        -1.0  0.000000e+00   
22071  8.596150e+04   2006278.0  2.006278e+06   2006278.0  0.000000e+00   

        min_idle  mean_idle   max_idle      std_idle     class1  
0      1234883.0  1420565.0  1523088.0  1.610965e+05  b'NONTOR'  
1      1131498.0  1324636.0  1517774.0  2.731384e+05  b'NONTOR'  
2      1079974.0  1079974.0  1079974.0  0.000000e+00  b'NONTOR'  
3      1346073.0  1894031.5  2441990.0  7.749303e+05  b'NONTOR'  
4      1394455.0  1983227.0  3042717.0  7.259878e+05  b'NONTOR'  
...          ...        ...        ...           ...        ...  
22067  1469335.0  4775651.0  8081967.0  4.675837e+06     b'TOR'  
22068  1288308.0  1456115.5  1623923.0  2.373156e+05     b'TOR'  
22069  5314745.0  6489046.0  7663347.0  1.660712e+06     b'TOR'  
22070       -1.0        0.0       -1.0  0.000000e+00     b'TOR'  
22071  1707073.0  1707073.0  1707073.0  0.000000e+00     b'TOR'  

[22072 rows x 24 columns]

In [6]:
df_data['class1'].value_counts()

b'NONTOR'    18758
b'TOR'        3314
Name: class1, dtype: int64

In [7]:
column_name = list(df_data.columns)

In [8]:
column_name

['duration',
 'total_fiat',
 'total_biat',
 'min_fiat',
 'min_biat',
 'max_fiat',
 'max_biat',
 'mean_fiat',
 'mean_biat',
 'flowPktsPerSecond',
 'flowBytesPerSecond',
 'min_flowiat',
 'max_flowiat',
 'mean_flowiat',
 'std_flowiat',
 'min_active',
 'mean_active',
 'max_active',
 'std_active',
 'min_idle',
 'mean_idle',
 'max_idle',
 'std_idle',
 'class1']

In [9]:
df_data.shape

(22072, 24)

In [10]:
print(df_data['class1'][0])

b'NONTOR'


Fixing that weird character 'b' problem.

In [11]:
df_data['class1'] = df_data['class1'].map(lambda val : 'NONTOR' if val == b'NONTOR' else 'TOR')

In [12]:
print(df_data['class1'][0])

NONTOR


In [13]:
df_data

duration  total_fiat  total_biat   min_fiat   min_biat      max_fiat  \
0       9368711.0        16.0         4.0  1564818.0  1549373.0  1.902053e+05   
1       7340238.0        18.0         4.0  1567554.0  1527893.0  1.656870e+05   
2       4644225.0        29.0        15.0  1270547.0  1079974.0  1.658652e+05   
3       4978735.0        19.0         8.0  2492050.0  2457286.0  2.395432e+05   
4      11838189.0        19.0        10.0  3094089.0  3093543.0  2.437665e+05   
...           ...         ...         ...        ...        ...           ...   
22067  13932812.0  13932390.0  13932812.0       93.0      244.0  8.119562e+06   
22068  14999975.0  14999975.0  14961989.0        0.0        7.0  1.624147e+06   
22069  14660517.0  14660517.0  14618019.0      333.0      613.0  7.663754e+06   
22070  14832948.0  14832905.0  14792242.0        7.0       12.0  7.884760e+05   
22071  14633355.0  14633355.0  14632000.0        6.0       34.0  1.707112e+06   

           max_biat     mean_fiat     mean_biat  flowPktsPerSecond  ...  \
0      2.032905e+05  3.898224e+05  3.703237e+05          10.353612  ...   
1      1.869148e+05  3.172675e+05  3.043707e+05          11.580006  ...   
2      1.953021e+05  3.294731e+05  3.004926e+05          11.412022  ...   
3      2.765964e+05  6.124353e+05  6.283396e+05           8.034169  ...   
4      2.959547e+05  5.997218e+05  6.256327e+05           7.602514  ...   
...             ...           ...           ...                ...  ...   
22067  8.081967e+06  3.240091e+05  2.843431e+05           6.746664  ...   
22068  1.624060e+06  2.103783e+04  2.939487e+04          81.600136  ...   
22069  7.663955e+06  1.628946e+06  1.827252e+06           1.295998  ...   
22070  8.250180e+05  4.324462e+04  4.350659e+04          46.180975  ...   
22071  1.707109e+06  4.180959e+04  4.766124e+04          45.034102  ...   

        std_flowiat  min_active   mean_active  max_active    std_active  \
0      2.676002e+05   1871488.0  1.983656e+06   2195089.0  1.832197e+05   
1      2.214629e+05   1491627.0  3.572433e+06   5653239.0  2.942704e+06   
2      2.174754e+05   1758922.0  1.758922e+06   1758922.0  0.000000e+00   
3      4.369597e+05   1710925.0  2.382905e+06   3054885.0  9.503232e+05   
4      4.361296e+05   1747431.0  2.400446e+06   3240696.0  6.232744e+05   
...             ...         ...           ...         ...           ...   
22067  8.490494e+05   1506874.0  6.966222e+06  12425570.0  7.720684e+06   
22068  7.020772e+04   3249302.0  3.525820e+06   3802338.0  3.910555e+05   
22069  2.116241e+06   6381394.0  7.023854e+06   7666315.0  9.085764e+05   
22070  6.915061e+04        -1.0  0.000000e+00        -1.0  0.000000e+00   
22071  8.596150e+04   2006278.0  2.006278e+06   2006278.0  0.000000e+00   

        min_idle  mean_idle   max_idle      std_idle  class1  
0      1234883.0  1420565.0  1523088.0  1.610965e+05  NONTOR  
1      1131498.0  1324636.0  1517774.0  2.731384e+05  NONTOR  
2      1079974.0  1079974.0  1079974.0  0.000000e+00  NONTOR  
3      1346073.0  1894031.5  2441990.0  7.749303e+05  NONTOR  
4      1394455.0  1983227.0  3042717.0  7.259878e+05  NONTOR  
...          ...        ...        ...           ...     ...  
22067  1469335.0  4775651.0  8081967.0  4.675837e+06     TOR  
22068  1288308.0  1456115.5  1623923.0  2.373156e+05     TOR  
22069  5314745.0  6489046.0  7663347.0  1.660712e+06     TOR  
22070       -1.0        0.0       -1.0  0.000000e+00     TOR  
22071  1707073.0  1707073.0  1707073.0  0.000000e+00     TOR  

[22072 rows x 24 columns]

In [14]:
dep_var = 'class1'
print(df_data[dep_var].value_counts())

NONTOR    18758
TOR        3314
Name: class1, dtype: int64


In [15]:
# Assign the lowest number of samples in a given classification (TOR in this case)
low_count = 3314

# Set a random state for reproducibility
random_state = 1

# Acquire all of the samples that fall into the TOR classification ( WHERE class is 'TOR' )
df1 = df_data.loc[ df_data[dep_var] == 'TOR']

print('Values in df1: ')
print(df1[dep_var].value_counts())

# Acquire all of the samples that fall into the NONTOR class ( WHERE class is 'NONTOR' )
df2 = df_data.loc[ df_data[dep_var] == 'NONTOR']

print('\nValues in df2: ')
print(df2[dep_var].value_counts())

Values in df1: 
TOR    3314
Name: class1, dtype: int64

Values in df2: 
NONTOR    18758
Name: class1, dtype: int64


## Balancing the dataset

In [16]:
df2 = df2.sample(low_count, random_state=random_state)

print('Values in df1: ')
print(df1[dep_var].value_counts())

print('\nValues in df2: ')
print(df2[dep_var].value_counts())

Values in df1: 
TOR    3314
Name: class1, dtype: int64

Values in df2: 
NONTOR    3314
Name: class1, dtype: int64


In [17]:
df = pd.concat([df1, df2])

print(df[dep_var].value_counts())

TOR       3314
NONTOR    3314
Name: class1, dtype: int64


In [18]:
df

duration  total_fiat  total_biat    min_fiat    min_biat  \
18758   2503844.0   2503725.0   2503548.0        54.0        10.0   
18759   8165087.0   8164944.0   8164678.0       793.0       507.0   
18760   7905757.0   7905757.0   7868987.0    347080.0       648.0   
18761  13011626.0  13011408.0  13011293.0       545.0       399.0   
18762  10614731.0  10614680.0  10574656.0      7339.0      7559.0   
...           ...         ...         ...         ...         ...   
12749  10400813.0    402296.0    300586.0   9646355.0  10048786.0   
13459      3891.0       338.0        85.0      1338.0       298.0   
1883   10004995.0  10004463.0         3.0  10004463.0  10004641.0   
4355   14998841.0        91.0         1.0     37756.0     37830.0   
8712   14830097.0         2.0     34722.0   2345315.0   2295311.0   

           max_fiat      max_biat     mean_fiat     mean_biat  \
18758  1.168796e+06  1.130894e+06  5.563833e+04  3.526124e+04   
18759  2.982860e+06  3.019690e+06  8.164944e+05  8.164678e+05   
18760  7.558677e+06  7.521931e+06  3.952878e+06  2.622996e+06   
18761  3.687359e+06  3.687369e+06  6.848109e+05  5.914224e+05   
18762  5.295363e+06  5.295378e+06  2.653670e+06  2.643664e+06   
...             ...           ...           ...           ...   
12749  5.024326e+06  5.174686e+06  6.536537e+06  6.893018e+06   
13459  7.782000e+02  2.192857e+02  4.948514e+02  7.184060e+01   
1883   1.000000e+07  5.002322e+06  0.000000e+00  7.074347e+06   
4355   1.841798e+04  1.687159e+04  5.133900e+03  6.203455e+03   
8712   7.118427e+05  1.018214e+06  7.221985e+05  6.698034e+05   

       flowPktsPerSecond  ...   std_flowiat  min_active   mean_active  \
18758          47.127537  ...  1.246777e+05   1875246.0  1.875246e+06   
18759           2.694399  ...  8.742063e+05   2215087.0  2.720941e+06   
18760           0.885431  ...  3.042497e+06   7869269.0  7.869269e+06   
18761           3.304737  ...  8.506981e+05   3005381.0  4.336276e+06   
18762           0.942087  ...  2.247411e+06   4979897.0  5.137638e+06   
...                  ...  ...           ...         ...           ...   
12749           0.576878  ...  4.231912e+06   9998517.0  9.998517e+06   
13459        3598.046775  ...  4.079628e+02        -1.0  0.000000e+00   
1883            0.499750  ...  5.001907e+06  10004641.0  1.000000e+07   
4355          113.608778  ...  6.509960e+03        -1.0  0.000000e+00   
8712            2.427496  ...  4.746069e+05   2345317.0  4.286155e+06   

       max_active    std_active    min_idle     mean_idle    max_idle  \
18758   1875246.0  0.000000e+00   1130894.0  1.130894e+06   1130894.0   
18759   3505946.0  6.892195e+05   2104581.0  2.434098e+06   2982806.0   
18760   7869269.0  0.000000e+00   7521931.0  7.521931e+06   7521931.0   
18761   6291854.0  1.730000e+06   3005119.0  3.281007e+06   3687107.0   
18762   5295378.0  2.230788e+05   4979846.0  5.137580e+06   5295313.0   
...           ...           ...         ...           ...         ...   
12749   9998517.0  0.000000e+00   9646355.0  9.646355e+06   9646355.0   
13459        -1.0  0.000000e+00        -1.0  0.000000e+00        -1.0   
1883   10004641.0  0.000000e+00  10004109.0  1.000000e+07  10004109.0   
4355         -1.0  0.000000e+00        -1.0  0.000000e+00        -1.0   
8712    6477688.0  2.077561e+06   1298314.0  1.764847e+06   2048759.0   

            std_idle  class1  
18758       0.000000     TOR  
18759  478385.920911     TOR  
18760       0.000000     TOR  
18761  359156.528488     TOR  
18762  223068.854938     TOR  
...              ...     ...  
12749       0.000000  NONTOR  
13459       0.000000  NONTOR  
1883        0.000000  NONTOR  
4355        0.000000  NONTOR  
8712   407191.290104  NONTOR  

[6628 rows x 24 columns]

In [19]:
combinedList = list(map(list, zip(df['duration'], df['total_fiat'], df['total_biat'], df['min_fiat'], df['min_biat'], df['max_fiat'], df['max_biat'], df['mean_fiat'], df['mean_biat'], df['flowPktsPerSecond'], df['flowBytesPerSecond'], df['min_flowiat'], df['max_flowiat'], df['mean_flowiat'], df['std_flowiat'], df['min_active'], df['mean_active'], df['max_active'], df['std_active'], df['min_idle'], df['mean_idle'], df['max_idle'], df['std_idle'])))

In [20]:
combinedList

[[2503844.0,
  2503725.0,
  2503548.0,
  54.0,
  10.0,
  1168796.0,
  1130894.0,
  55638.3333333333,
  35261.2394366197,
  47.1275366996,
  35286.5434108515,
  6.0,
  1130894.0,
  21400.3760683761,
  124677.73059975,
  1875246.0,
  1875246.0,
  1875246.0,
  0.0,
  1130894.0,
  1130894.0,
  1130894.0,
  0.0],
 [8165087.0,
  8164944.0,
  8164678.0,
  793.0,
  507.0,
  2982860.0,
  3019690.0,
  816494.4,
  816467.8,
  2.6943987247,
  1028.158058818,
  54.0,
  2982806.0,
  388813.666666667,
  874206.348383483,
  2215087.0,
  2720940.66666667,
  3505946.0,
  689219.471011835,
  2104581.0,
  2434098.33333333,
  2982806.0,
  478385.920910966],
 [7905757.0,
  7905757.0,
  7868987.0,
  347080.0,
  648.0,
  7558677.0,
  7521931.0,
  3952878.5,
  2622995.66666667,
  0.8854307058,
  310.1537272142,
  258.0,
  7521931.0,
  1317626.16666667,
  3042497.12746119,
  7869269.0,
  7869269.0,
  7869269.0,
  0.0,
  7521931.0,
  7521931.0,
  7521931.0,
  0.0],
 [13011626.0,
  13011408.0,
  13011293.0,
  545

In [21]:
df['class1'] = df['class1'].map(lambda val : 0 if val == 'NONTOR' else 1)

In [22]:
df['class1']

18758    1
18759    1
18760    1
18761    1
18762    1
        ..
12749    0
13459    0
1883     0
4355     0
8712     0
Name: class1, Length: 6628, dtype: int64

In [23]:
df

duration  total_fiat  total_biat    min_fiat    min_biat  \
18758   2503844.0   2503725.0   2503548.0        54.0        10.0   
18759   8165087.0   8164944.0   8164678.0       793.0       507.0   
18760   7905757.0   7905757.0   7868987.0    347080.0       648.0   
18761  13011626.0  13011408.0  13011293.0       545.0       399.0   
18762  10614731.0  10614680.0  10574656.0      7339.0      7559.0   
...           ...         ...         ...         ...         ...   
12749  10400813.0    402296.0    300586.0   9646355.0  10048786.0   
13459      3891.0       338.0        85.0      1338.0       298.0   
1883   10004995.0  10004463.0         3.0  10004463.0  10004641.0   
4355   14998841.0        91.0         1.0     37756.0     37830.0   
8712   14830097.0         2.0     34722.0   2345315.0   2295311.0   

           max_fiat      max_biat     mean_fiat     mean_biat  \
18758  1.168796e+06  1.130894e+06  5.563833e+04  3.526124e+04   
18759  2.982860e+06  3.019690e+06  8.164944e+05  8.164678e+05   
18760  7.558677e+06  7.521931e+06  3.952878e+06  2.622996e+06   
18761  3.687359e+06  3.687369e+06  6.848109e+05  5.914224e+05   
18762  5.295363e+06  5.295378e+06  2.653670e+06  2.643664e+06   
...             ...           ...           ...           ...   
12749  5.024326e+06  5.174686e+06  6.536537e+06  6.893018e+06   
13459  7.782000e+02  2.192857e+02  4.948514e+02  7.184060e+01   
1883   1.000000e+07  5.002322e+06  0.000000e+00  7.074347e+06   
4355   1.841798e+04  1.687159e+04  5.133900e+03  6.203455e+03   
8712   7.118427e+05  1.018214e+06  7.221985e+05  6.698034e+05   

       flowPktsPerSecond  ...   std_flowiat  min_active   mean_active  \
18758          47.127537  ...  1.246777e+05   1875246.0  1.875246e+06   
18759           2.694399  ...  8.742063e+05   2215087.0  2.720941e+06   
18760           0.885431  ...  3.042497e+06   7869269.0  7.869269e+06   
18761           3.304737  ...  8.506981e+05   3005381.0  4.336276e+06   
18762           0.942087  ...  2.247411e+06   4979897.0  5.137638e+06   
...                  ...  ...           ...         ...           ...   
12749           0.576878  ...  4.231912e+06   9998517.0  9.998517e+06   
13459        3598.046775  ...  4.079628e+02        -1.0  0.000000e+00   
1883            0.499750  ...  5.001907e+06  10004641.0  1.000000e+07   
4355          113.608778  ...  6.509960e+03        -1.0  0.000000e+00   
8712            2.427496  ...  4.746069e+05   2345317.0  4.286155e+06   

       max_active    std_active    min_idle     mean_idle    max_idle  \
18758   1875246.0  0.000000e+00   1130894.0  1.130894e+06   1130894.0   
18759   3505946.0  6.892195e+05   2104581.0  2.434098e+06   2982806.0   
18760   7869269.0  0.000000e+00   7521931.0  7.521931e+06   7521931.0   
18761   6291854.0  1.730000e+06   3005119.0  3.281007e+06   3687107.0   
18762   5295378.0  2.230788e+05   4979846.0  5.137580e+06   5295313.0   
...           ...           ...         ...           ...         ...   
12749   9998517.0  0.000000e+00   9646355.0  9.646355e+06   9646355.0   
13459        -1.0  0.000000e+00        -1.0  0.000000e+00        -1.0   
1883   10004641.0  0.000000e+00  10004109.0  1.000000e+07  10004109.0   
4355         -1.0  0.000000e+00        -1.0  0.000000e+00        -1.0   
8712    6477688.0  2.077561e+06   1298314.0  1.764847e+06   2048759.0   

            std_idle  class1  
18758       0.000000       1  
18759  478385.920911       1  
18760       0.000000       1  
18761  359156.528488       1  
18762  223068.854938       1  
...              ...     ...  
12749       0.000000       0  
13459       0.000000       0  
1883        0.000000       0  
4355        0.000000       0  
8712   407191.290104       0  

[6628 rows x 24 columns]

### Class1 column is going to be our target which is 'y' and list of other column (combinedList) is going to be our 'X'

In [24]:
target_value = list()

In [25]:
for d in df['class1']:
    target_value.append(d)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
random_state = 1
X = combinedList
y = target_value

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=random_state, stratify=y)

In [29]:
X_train

[[14950789.0,
  14924646.0,
  14950370.0,
  8.0,
  63.0,
  93577.0,
  122366.0,
  19663.5652173913,
  24549.0476190476,
  91.6339599201,
  37011.4246144468,
  8.0,
  93365.0,
  10920.9561723886,
  14290.1605196433,
  -1.0,
  0.0,
  -1.0,
  0.0,
  -1.0,
  0.0,
  -1.0,
  0.0],
 [14992573.0,
  140.0,
  25.0,
  3572095.0,
  3477273.0,
  409733.333333333,
  309418.833333333,
  823300.915989895,
  684075.748051179,
  5.736173504,
  273.5354365125,
  13.0,
  3327263.0,
  176383.211764706,
  500207.197816055,
  2563441.0,
  3650089.0,
  6723236.0,
  2049296.48255143,
  1650720.0,
  2285995.5,
  3327263.0,
  724895.677687946],
 [14997631.0,
  59.0,
  50.0,
  23917.0,
  173632.0,
  18047.6907340554,
  43807.853372434,
  4708.462973382,
  28278.4436685733,
  78.2790295347,
  11479.5463363514,
  50.0,
  23917.0,
  12785.7041773231,
  6774.4497375717,
  -1.0,
  0.0,
  -1.0,
  0.0,
  -1.0,
  0.0,
  -1.0,
  0.0],
 [14970698.0,
  14970508.0,
  14889122.0,
  14.0,
  0.0,
  202572.0,
  242250.0,
  27519

In [30]:
print("Number of training samples: {}".format(len(X_train)))
print("Number of testing samples: {}".format(len(X_test)))

Number of training samples: 5302
Number of testing samples: 1326


In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier


In [32]:
randomForest = RandomForestClassifier(max_depth=2, random_state=random_state)
decisionTree = DecisionTreeClassifier(random_state = random_state)

In [33]:
randomForest.fit(X_train, y_train)
print("Random Forest fitted")
decisionTree.fit(X_train, y_train)
print("Decision Tree fitted")

Random Forest fitted
Decision Tree fitted


/home/bishal/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [34]:
randomForestResult = randomForest.score(X_test, y_test)
decisionTreeResult = decisionTree.score(X_test, y_test)

In [35]:
print('Random Forest: {:.2f}'.format(randomForestResult))
print('Decision Tree: {:.2f}'.format(decisionTreeResult))

Random Forest: 0.99
Decision Tree: 0.99


We have 99% accuracy with both random forest and decision tree machine learning classifier. Now, let us perform some Deep neural network.

# Performing DNN

In [36]:
from keras.models import Sequential
from keras.layers import Dense
from keras.metrics import CategoricalAccuracy, Precision, Recall
from keras.utils import to_categorical
print('Importing relevant libraries for deep learning model')

Using TensorFlow backend.


Importing relevant libraries for deep learning model


In [37]:
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)

In [38]:
print('y_train values:')
print(y_train)

print('y_test values:')
print(y_test)

y_train values:
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
y_test values:
[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [39]:
accuracy = CategoricalAccuracy() 
prec = Precision()
rec = Recall()
metrics = [accuracy, prec, rec]

model = Sequential()
model.add(Dense(32, input_shape=(23,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=metrics)

In [40]:
print(len(X_train[0]))

23


## converting X-train into numpy arrays into the variable a

In [41]:
a = np.array(X_train)

In [42]:
a

array([[ 1.49507890e+07,  1.49246460e+07,  1.49503700e+07, ...,
         0.00000000e+00, -1.00000000e+00,  0.00000000e+00],
       [ 1.49925730e+07,  1.40000000e+02,  2.50000000e+01, ...,
         2.28599550e+06,  3.32726300e+06,  7.24895678e+05],
       [ 1.49976310e+07,  5.90000000e+01,  5.00000000e+01, ...,
         0.00000000e+00, -1.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.49772320e+07,  1.49772320e+07,  1.49557550e+07, ...,
         0.00000000e+00, -1.00000000e+00,  0.00000000e+00],
       [ 1.40710500e+07,  8.20000000e+01,  9.40000000e+01, ...,
         6.87497100e+06,  1.00000480e+07,  4.41952628e+06],
       [ 1.49965390e+07,  1.49962490e+07,  1.49965390e+07, ...,
         1.33289000e+06,  1.74807900e+06,  3.08410336e+05]])

## Fitting the model

In [43]:
model.fit(a, y=y_train, epochs=20, batch_size=5, verbose=0)

## storing the X_test array as numpy arrays into the variable b

In [44]:
b = np.array(X_test)

In [45]:
results_dnn = model.evaluate(b, y_test, verbose=0)
acc, prec, rec = results_dnn[1]*100, results_dnn[2], results_dnn[3]
print('Accuracy: {:.2f}%'.format(acc))
print('Precision: {:.2f}'.format(prec))
print('Recall: {:.2f}'.format(rec))

Accuracy: 99.77%
Precision: 1.00
Recall: 1.00


The accuracy with deep learning model is 99.77%.